name: Use Reusable CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  call-reusable:
    uses: olu-folarin/basic-gha/.github/workflows/ci.yaml@main
    with: {}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      PAT_FOR_WORKFLOW: ${{ secrets.PAT_FOR_WORKFLOW }}
